### ISSUE TITLE
configparser import error ExtendedInterpolation

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/konfig#12]
- konfig==0.9
- configparser==3.3.0.post2

```
INFO:venusian:Created PostgreSQL permission tables 
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto/.venv/bin/loads-runner", line 9, in <module>
    load_entry_point('loads==0.3', 'console_scripts', 'loads-runner')()
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
    return ep.load()
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2379, in load
    return self.resolve()
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2385, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/loads/main.py", line 7, in <module>
    from konfig import Config
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/konfig/__init__.py", line 11, in <module>
    from configparser import ConfigParser, ExtendedInterpolation
ImportError: cannot import name ExtendedInterpolation
```

**Comment by leplatrem** [comment]
* konfig==0.9
* configparser==3.5.0

**Comment by tarekziade** [comment]
Cannot reproduce the issue, ExtendedInterpolation exists in configparser 3.5.0 and I could import it. If you have a test that reproduces the problem please reopen this bug
